account/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('registro/', views.register, name='register'),
    path('endereco/', views.update_address, name='update_endereco'),
]

checkout/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<str:slug>/', views.create_cartitem, name='create_cartitem'),
    path('carrinho/', views.cart_item, name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro/', views.pagseguro_view, name='pagseguro_view'),
    path('finalizando/<int:pk>/paypal/', views.paypal_view, name='paypal_view'),
    path('notificacoes/pagseguro/', views.pagseguro_notification, name='pagseguro_notification'),
    path('meus-pedidos/', views.order_list, name='order_list'),
    path('meus-pedidos/<int:pk>/', views.order_detail, name='order_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from areadocliente.views import areadocliente
from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('areacliente/', areadocliente),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalogo/', include('catalog.urls')),
    path('conta/', include('account.urls')),
    path('compras/', include('checkout.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

account/models.py
# coding=utf-8
import re

from django.core import validators
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, UserManager, PermissionsMixin)

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido / Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os caracteres: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Um nome curto que será usado para identificá-lo de forma única na plataforma'
    )
    name = models.CharField('Nome', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    rua = models.CharField('Rua', max_length=240, null=True)
    numero = models.CharField('Número', max_length=20, null=True)
    complemento = models.CharField('Complemento', max_length=200, null=True)
    bairro = models.CharField('Bairro', max_length=100, null=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

account/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'name', 'email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']


class UpdateAddressForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['rua', 'numero', 'complemento', 'bairro']

account/views.py
# coding=utf-8

from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView
)
from .models import User
from .forms import UserAdminCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

# Create your views here.


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/index.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('account:index')

    def get_object(self):
        return self.request.user


class UpdateAddressView(LoginRequiredMixin, UpdateView):

    model = User
    template_name = 'accounts/update_address.html'
    fields = ['rua', 'numero', 'complemento', 'bairro']
    success_url = reverse_lazy('account:index')

    def get_object(self):
        return self.request.user


class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('account:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)


index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()
update_address = UpdateAddressView.as_view()

account/templates/accounts/index.html
 {% extends 'base.html' %}

 {% block title %} Minha conta {% endblock %}

{% block container %}
 <!--================Product Description Area =================-->
	<section class="product_description_area">
		<div class="container">

			<ul class="nav nav-tabs" id="myTab" role="tablist">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account:index' %}" >Minha Conta</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account:update_user' %}" >Alterar Dados</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account:update_endereco' %}" >Endereço</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account:update_password' %}">Alterar Senha</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'checkout:order_list' %}">Meus Pedidos</a>
				</li>
			</ul>
			<div class="tab-content" id="myTabContent">
				<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
					<div class="col-md-12">
                {% block account_container %}
                    <h2 style="text-align: center;">Bem vindo(a) {{ user.name }}</h2>
                {% endblock %}
            </div>
				</div>

			</div>
		</div>
	</section>
	<!--================End Product Description Area =================-->
{% endblock %}

account/templates/accounts/register.html
{% extends "base.html" %}


{% block title %}
    Registro | {{ block.super }}
{% endblock %}

{% block container %}
<style>
    input{
        display: block;
        width: 100%;
        padding: 8px 16px;
        line-height: 25px;
        font-size: 14px;
        font-weight: 500;
        font-family: inherit;
        border-radius: 6px;
        -webkit-appearance: none;
        color: black;
        border: 1px solid var(--input-border);
        background: #f1f6f7;
        transition: border .3s ease;
    }
</style>
<!--================Login Box Area =================-->
	<section class="login_box_area section-margin">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="login_box_img" style="height: 697px;">
						<div class="hover">
							<h4>Already have an account?</h4>
							<p>There are advances being made in science and technology everyday, and a good example of this is the</p>
							<a class="button button-account" href="{% url 'login' %}">Login</a>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="login_form_inner register_form_inner">
						<h3>Criar sua conta</h3>
						<form class="row login_form" method="post">
                            {% csrf_token %}
                            {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% for field in form %}
                            <div class="col-md-12 form-group{% if field.errors %} has-error{% endif %}">
                                <label for="{{ field.auto_id }}" class="col-md-12 control-label">{{ field.label }}</label>
								 {{ field }}
							</div>
                            {% endfor %}

							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="button button-register w-100">Criar sua conta</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Login Box Area =================-->
{% endblock %}

account/templates/accounts/update_address.html
{% extends "accounts/index.html" %}


{% block title %}Alterar endereço{% endblock %}

{% block account_container %}
<style>
    input{
        display: block;
        width: 100%;
        padding: 8px 16px;
        line-height: 25px;
        font-size: 14px;
        font-weight: 500;
        font-family: inherit;
        border-radius: 6px;
        -webkit-appearance: none;
        color: black;
        border: 1px solid var(--input-border);
        background: #f1f6f7;
        transition: border .3s ease;

    }
</style>
    <h2>Alterar Endereço</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-12">
                {{ field }}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Atualizar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

account/templates/accounts/update_password.html
</{% extends "accounts/index.html" %}


{% block title %}Alterar Senha{% endblock %}

{% block account_container %}
<style>
    input{
        display: block;
        width: 100%;
        padding: 8px 16px;
        line-height: 25px;
        font-size: 14px;
        font-weight: 500;
        font-family: inherit;
        border-radius: 6px;
        -webkit-appearance: none;
        color: black;
        border: 1px solid var(--input-border);
        background: #f1f6f7;
        transition: border .3s ease;

    }
</style>
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-12">
                {{ field }}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

account/templates/accounts/update_user.html
{% extends "accounts/index.html" %}


{% block title %}Alterar Dados{% endblock %}

{% block account_container %}
<style>
    input{
        display: block;
        width: 100%;
        padding: 8px 16px;
        line-height: 25px;
        font-size: 14px;
        font-weight: 500;
        font-family: inherit;
        border-radius: 6px;
        -webkit-appearance: none;
        color: black;
        border: 1px solid var(--input-border);
        background: #f1f6f7;
        transition: border .3s ease;

    }
</style>
    <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-12">
                {{ field }}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Atualizar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}