account/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('registro/', views.register, name='register'),
    path('endereco/', views.update_address, name='update_endereco'),
]

catalog/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<str:slug>/', views.category, name='category'),
    path('produtos/<str:slug>/', views.product, name='product'),
]

checkout/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<str:slug>/', views.create_cartitem, name='create_cartitem'),
    path('carrinho/', views.cart_item, name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro/', views.pagseguro_view, name='pagseguro_view'),
    path('finalizando/<int:pk>/paypal/', views.paypal_view, name='paypal_view'),
    path('notificacoes/pagseguro/', views.pagseguro_notification, name='pagseguro_notification'),
    path('meus-pedidos/', views.order_list, name='order_list'),
    path('meus-pedidos/<int:pk>/', views.order_detail, name='order_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from areadocliente.views import areadocliente
from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('areacliente/', areadocliente),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalogo/', include('catalog.urls')),
    path('conta/', include('account.urls')),
    path('compras/', include('checkout.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContactForm(forms.Form):
    name = forms.CharField(label='Nome', widget=forms.TextInput(attrs={'placeholder': 'Nome', 'class': 'form-control'}))
    email = forms.EmailField(label='Email',
                             widget=forms.TextInput(attrs={'placeholder': 'E-mail', 'class': 'form-control'}))
    message = forms.CharField(label='Mensagem',
                              widget=forms.Textarea(
                                  attrs={'placeholder': 'Mensagem', 'class': 'form-control different-control w-100', 'cols': 30, 'rows': 5}))

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nE-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Contato E-commerce Django', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

core/views.py
# coding=utf-8
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from core.forms import ContactForm
from django.contrib import messages
from django.views import generic
from watson import search as watson

from catalog.models import Product

User = get_user_model()


class IndexView(generic.ListView):

    template_name = 'index.html'

    paginate_by = 12

    # Pesquisando no formulario de pesquisa (Filtrando pelo título do Produto | pelo nome da Categoria | pela descrição do produto

    def get_queryset(self):
        queryset = Product.objects.all()
        q = self.request.GET.get('q', '')
        if q:
            queryset = watson.filter(queryset, q)
        return queryset


index = IndexView.as_view()


def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
    elif request.method == 'POST':
        messages.error(request, 'Formulário inválido')
    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)


class RegisterView(CreateView):

    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    model = User
    success_url = reverse_lazy('index')


register = RegisterView.as_view()

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}E-commerce{% endblock %}</title>
	<link rel="icon" href="{% static 'assets/img/Fevicon.png' %}" type="image/png">
  <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/nice-select/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel/owl.carousel.min.css' %}">

  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	<style>
		.logo_ecommerce {
			max-width:115px;
			max-height:150px;
			width: auto;
			height: auto;
			margin-left: 50%;
		}
	</style>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-165464364-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-165464364-1');
</script>
<style>
	.instagram{
	}
img.box {
    width: 150px;
    display: inline-block;
}
</style>
</head>
<body>
  <!--================ Start Header Menu Area =================-->
	<header class="header_area">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand logo_h" style="margin-left: -6%;" href="{% url 'index' %}"><img class="logo_ecommerce" src="{% static 'assets/img/logo_ecommerce2.png' %}" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
            <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
              <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Início</a></li>
              <li class="nav-item submenu dropdown">
                <a href="{% url 'catalog:product_list' %}" class="nav-link" role="button">Produtos</a>
							</li>
              <li class="nav-item submenu dropdown">
                <a href="{% url 'catalog:product_list' %}" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false">Categorias</a>
                <ul class="dropdown-menu">
					{% for category in categories %}
                  <li class="nav-item"><a class="nav-link" href="{{ category.get_absolute_url }}">{{ category }}</a></li>
					{% endfor %}
                </ul>
							</li>

              <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contato</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">|</a></li>
              {% if user.is_authenticated %}
				<li class="nav-item"><a class="nav-link"><b style="text-transform: none;">Bem vindo(a): {{ user.username }}</b></a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'account:index' %}" style="color: green;">Conta</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}" style="color: green;">Sair</a></li>
                  {% else %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Entrar</a></li>
                  <!--<li class="nav-item"><a class="nav-link" href="{% url 'account:register' %}">Cadastro</a></li>-->
              {% endif %}
            </ul>

            <ul class="nav-shop">
              <li class="nav-item">
				  <form class="navbar-form navbar-left" role="search" action="{% url 'catalog:product_list' %}">
	        <div class="form-group">
	          <input style="margin-top: 8%;" name="q" type="text" class="form-control" placeholder="Pesquisar..." />
	        </div>
	      </form>
			  </li>
              <li class="nav-item"><a href="{% url 'checkout:cart_item' %}"><button><i class="ti-shopping-cart"></i><span class="nav-shop__circle"></span></button></a></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
		<div class="container margin-top">
    <br>
        {% block messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}

        {% endblock %}
    </div>
  </header>
	<!--================ End Header Menu Area =================-->

  {% block container %}{% endblock %}

	<br><br>
  <!--================ Start footer Area  =================-->
	<footer class="footer">
		<div class="footer-area">
			<div class="container">
				<div class="row section_gap">
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title large_title">Sobre</h4>
							<p style="text-align: justify;">
								Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
							</p>
						</div>
					</div>
					<div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Menu</h4>
							<ul class="list">
								<li><a href="{% url 'index' %}">Início</a></li>
								<li><a href="{% url 'catalog:product_list' %}">Produtos</a></li>
								<li><a href="{% url 'contact' %}">Contato</a></li>
								<li><a href="{% url 'login' %}">Entrar</a></li>
							</ul>
						</div>
					</div>
					<!--<div class="col-lg-2 col-md-8 col-sm-6">
						<div class="single-footer-widget instafeed">
							<h4 class="footer_title">Instagram</h4>
							<ul class="list instafeed d-flex flex-wrap">
								<div class="posts"></div>
							</ul>
						</div>
					</div>-->
					<div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Contato</h4>
							<div class="ml-40">
								<p class="sm-head">
									<span class="fa fa-location-arrow"></span>
									Escritório
								</p>
								<p>Boa Vista - Roraima, 232</p>

								<p class="sm-head">
									<span class="fa fa-phone"></span>
									Telefone
								</p>
								<p>
									(95) 98818-9425
								</p>

								<p class="sm-head">
									<span class="fa fa-envelope"></span>
									Email
								</p>
								<p>
									maurodenison@gmail.com
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row d-flex">
					<p class="col-lg-12 footer-text text-center">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</div>
		</div>
	</footer>
	<!--================ End footer Area  =================-->



  <script src="{% static 'assets/vendors/jquery/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendors/skrollr.min.js' %}"></script>
  <script src="{% static 'assets/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/vendors/nice-select/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'assets/vendors/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{% static 'assets/vendors/mail-script.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
<!-- INSTAGRAM -->
<script>
  function nFormatter(num) {
    if (num >= 1000000000) {
      return (num / 1000000000).toFixed(1).replace(/\.0$/, '') + 'G';
    }
    if (num >= 1000000) {
      return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M';
    }
    if (num >= 1000) {
      return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
    }
    return num;
  }
  $.ajax({
    url: "https://www.instagram.com/miniaturasmaceio?__a=1",
    type: 'get',
    success: function(response) {
      posts = response.graphql.user.edge_owner_to_timeline_media.edges;
      posts_html = '';
      for (var i = 0; i < posts.length; i++) {
        url = posts[i].node.display_url;
        likes = posts[i].node.edge_liked_by.count;
        comments = posts[i].node.edge_media_to_comment.count;
	posts_html += '<a href="' + url + '"><img class="box" src="' + url + '"></a>';
        // Post Original
        //posts_html += '<div class="col-md-4 equal-height"><a href="'+url+'"><img style="min-height:50px;background-color:#fff;width:100%" src="'+url+'"></a><div class="row like-comment"><div class="col-md-6">'+nFormatter(likes)+' Curtidas</div><div class="col-md-6">'+nFormatter(comments)+' Comentários</div></div></div>';
      }
      $(".posts").html(posts_html);
    }
  });
</script>
<!-- INSTAGRAM -->
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<!-- ================ contact section start ================= -->
  <section class="section-margin--small">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-lg-3 mb-4 mb-md-0">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Boa Vista - Roraima</h3>
              <p>Canarinho</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-headphone"></i></span>
            <div class="media-body">
              <h3><a href="tel:454545654">(95) 98118-9425</a></h3>
              <p>Segunda à Sexta 8:00 às 18:00</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3><a href="mailto:support@colorlib.com">maurodenison@gmail.com</a></h3>
              <p>Nos envie sua dúvida!</p>
            </div>
          </div>
        </div>
        <div class="col-md-8 col-lg-9">
			{% if success %}
                <div class="alert alert-success">
                    Mensagem enviada com sucesso.
                </div>
            {% endif %}
          <form action="" class="form-contact contact_form" method="post" id="contactForm">
			  {% csrf_token %}
            <div class="row">
              <div class="col-lg-5">
                <div class="form-group">
					{{ form.name }}
                </div>
                <div class="form-group">
					{{ form.email }}
                </div>
              </div>
              <div class="col-lg-7">
                <div class="form-group">
					{{ form.message }}
				</div>
              </div>
            </div>
            <div class="form-group text-center text-md-right mt-3">
              <button type="submit" class="button button--active button-contactForm">Enviar mensagem</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load pagination %}
{% block container %}
    <main class="site-main">

    <!--================ Hero banner start =================-->
    <section class="hero-banner">
      <div class="container">
        <div class="row no-gutters align-items-center pt-60px">
          <div class="col-5 d-none d-sm-block">
            <div class="hero-banner__img">
              <img class="img-fluid" src="{% static 'assets/img/home/hero-banner.png' %}" alt="">
            </div>
          </div>
          <div class="col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
            <div class="hero-banner__content">
              <h4>Shop is fun</h4>
              <h1>Browse Our Premium Product</h1>
              <p>Us which over of signs divide dominion deep fill bring they're meat beho upon own earth without morning over third. Their male dry. They are great appear whose land fly grass.</p>
              <a class="button button-hero" href="#">Browse Now</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================ Hero banner start =================-->

    <!--================ Hero Carousel start =================-->
    <section class="section-margin mt-0">
      <div class="owl-carousel owl-theme hero-carousel">
        <div class="hero-carousel__slide">
          <img src="{% static 'assets/img/home/hero-slide1.png' %}" alt="" class="img-fluid">
          <a href="#" class="hero-carousel__slideOverlay">
            <h3>Wireless Headphone</h3>
            <p>Accessories Item</p>
          </a>
        </div>
        <div class="hero-carousel__slide">
          <img src="{% static 'assets/img/home/hero-slide2.png' %}" alt="" class="img-fluid">
          <a href="#" class="hero-carousel__slideOverlay">
            <h3>Wireless Headphone</h3>
            <p>Accessories Item</p>
          </a>
        </div>
        <div class="hero-carousel__slide">
          <img src="{% static 'assets/img/home/hero-slide3.png' %}" alt="" class="img-fluid">
          <a href="#" class="hero-carousel__slideOverlay">
            <h3>Wireless Headphone</h3>
            <p>Accessories Item</p>
          </a>
        </div>
      </div>
    </section>
    <!--================ Hero Carousel end =================-->

    <!-- ================ trending product section start ================= -->
    <section class="section-margin calc-60px">
      <div class="container">
        <div class="section-intro pb-60px">
          <h2>Produtos</span></h2>
        </div>
        <div class="row">

            {% for product in product_list %}
            {% include "catalog/_product.html" %}
            {% endfor %}

        </div>
      </div>
    </section>
    <!-- ================ trending product section end ================= -->


    <!-- ================ offer section start ================= -->
    <section class="offer" id="parallax-1" data-anchor-target="#parallax-1" data-300-top="background-position: 20px 30px" data-top-bottom="background-position: 0 20px">
      <div class="container">
        <div class="row">
          <div class="col-xl-5">
            <div class="offer__content text-center">
              <h3>Up To 50% Off</h3>
              <h4>Winter Sale</h4>
              <p>Him she'd let them sixth saw light</p>
              <a class="button button--active mt-3 mt-xl-4" href="#">Shop Now</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ offer section end ================= -->

    <br><br><br><br>

    <!-- ================ Blog section start ================= -->
    <section class="blog">
      <div class="container">
        <div class="section-intro pb-60px">
          <h2>Blog</span></h2>
        </div>

        <div class="row">
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="card card-blog">
              <div class="card-blog__img">
                <img class="card-img rounded-0" src="{% static 'assets/img/blog/blog1.png' %}" alt="">
              </div>
              <div class="card-body">
                <ul class="card-blog__info">
                  <li><a href="#">By Admin</a></li>
                  <li><a href="#"><i class="ti-comments-smiley"></i> 2 Comments</a></li>
                </ul>
                <h4 class="card-blog__title"><a href="single-blog.html">The Richland Center Shooping News and weekly shooper</a></h4>
                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>
                <a class="card-blog__link" href="#">Visualizar <i class="ti-arrow-right"></i></a>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="card card-blog">
              <div class="card-blog__img">
                <img class="card-img rounded-0" src="{% static 'assets/img/blog/blog2.png' %}" alt="">
              </div>
              <div class="card-body">
                <ul class="card-blog__info">
                  <li><a href="#">By Admin</a></li>
                  <li><a href="#"><i class="ti-comments-smiley"></i> 2 Comments</a></li>
                </ul>
                <h4 class="card-blog__title"><a href="single-blog.html">The Shopping News also offers top-quality printing services</a></h4>
                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>
                <a class="card-blog__link" href="#">Visualizar <i class="ti-arrow-right"></i></a>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="card card-blog">
              <div class="card-blog__img">
                <img class="card-img rounded-0" src="{% static 'assets/img/blog/blog3.png' %}" alt="">
              </div>
              <div class="card-body">
                <ul class="card-blog__info">
                  <li><a href="#">By Admin</a></li>
                  <li><a href="#"><i class="ti-comments-smiley"></i> 2 Comments</a></li>
                </ul>
                <h4 class="card-blog__title"><a href="single-blog.html">Professional design staff and efficient equipment you’ll find we offer</a></h4>
                <p>Let one fifth i bring fly to divided face for bearing divide unto seed. Winged divided light Forth.</p>
                <a class="card-blog__link" href="#">Visualizar <i class="ti-arrow-right"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ Blog section end ================= -->
  </main>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% block title %}
    Entrar | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% form.username  %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% form.password %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Entrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

core/templates/pagination.html
<nav class="blog-pagination justify-content-center d-flex">
                          <ul class="pagination">
                    {% for page in paginator.page_range %}
                        <li{% if page_obj.number == page %} class="page-item active"{% endif %}><a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
                    {% endfor %}

                </ul>
            </nav>