account/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('registro/', views.register, name='register'),
    path('endereco/', views.update_address, name='update_endereco'),
]

catalog/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<str:slug>/', views.category, name='category'),
    path('produtos/<str:slug>/', views.product, name='product'),
]

checkout/urls.py
# coding=utf-8

from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('carrinho/adicionar/<str:slug>/', views.create_cartitem, name='create_cartitem'),
    path('carrinho/', views.cart_item, name='cart_item'),
    path('finalizando/', views.checkout, name='checkout'),
    path('finalizando/<int:pk>/pagseguro/', views.pagseguro_view, name='pagseguro_view'),
    path('finalizando/<int:pk>/paypal/', views.paypal_view, name='paypal_view'),
    path('notificacoes/pagseguro/', views.pagseguro_notification, name='pagseguro_notification'),
    path('meus-pedidos/', views.order_list, name='order_list'),
    path('meus-pedidos/<int:pk>/', views.order_detail, name='order_detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from areadocliente.views import areadocliente
from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('areacliente/', areadocliente),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalogo/', include('catalog.urls')),
    path('conta/', include('account.urls')),
    path('compras/', include('checkout.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

catalog/models.py
# coding=utf-8

from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})


class Product(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria', on_delete=models.CASCADE)
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    image = models.ImageField(
        'Imagem', upload_to='products', blank=True, null=True
    )
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

catalog/views.py
# coding=utf-8
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Product, Category
from watson import search as watson
from django.views.decorators.cache import cache_page


class ProductListView(generic.ListView):

    template_name = 'catalog/product_list.html'
    paginate_by = 9

    # Pesquisando no formulario de pesquisa (Filtrando pelo título do Produto | pelo nome da Categoria | pela descrição do produto

    def get_queryset(self):
        queryset = Product.objects.all()
        q = self.request.GET.get('q', '')
        if q:
            queryset = watson.filter(queryset, q)
        return queryset


product_list = ProductListView.as_view()


class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 9

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(
            Category, slug=self.kwargs['slug'])
        return context


category = CategoryListView.as_view()

# Cache de 60 segundos na pagina de produtos
def product(request, slug):
    product = Product.objects.get(slug=slug)

    context = {
        'product': product,
    }
    return render(request, 'catalog/product.html', context)

catalog/templates/catalog/_product.html
{% load thumbnail %}
<div class="col-md-6 col-lg-4">
    <div class="card text-center card-product">
      <div class="card-product__img">
          {% if product.image %}
        <img class="card-img" style="border-radius: 3%;" src="{{ product.image|thumbnail_url:'product_image' }}" alt="">
          {% else %}
          <img class="card-img" src="http://placehold.it/350x250" alt="">
          {% endif %}
        <ul class="card-product__imgOverlay">
            <li><a href="{{ product.get_absolute_url }}"><button><i class="ti-search"></i></button></a></li>
            <li><a href="{% url 'checkout:create_cartitem' product.slug %}"><button><i class="ti-shopping-cart"></i></button></a></li>
        </ul>
      </div>

      <div class="card-body">
        <h4 class="card-product__title"><a href="#">{{ product }}</a></h4>
        <p class="card-product__price">R$ {{ product.price }}</p>
      </div>
    </div>
</div>

catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}


    <section class="section-margin--small mb-5">

        <div class="container">
          <div class="row">
            <div class="col-xl-3 col-lg-4 col-md-5">
                <div class="sidebar-filter">
                </div>
              </div>
            </div>

            <div class="col-xl-12 col-lg-8 col-md-7">
                <h1>{{ current_category }}</h1><br><br>
              <section class="lattest-product-area pb-40 category-list">
                <div class="row">
                    {% for product in product_list %}
                    {% include "catalog/_product.html" %}
                    {% endfor %}
                </div>
              </section>
              <!-- End Best Seller -->
            </div>
          </div>
        </div>
    </section>
    {% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/category_detail.html
<h1>Detalhes do Produto</h1>

catalog/templates/catalog/product.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
    {{ product }} | {{ block.super }}
{% endblock %}
{% load static %}
{% block container %}
    <!--================Single Product Area =================-->
	<div class="product_image_area">
		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
					<div class="owl-carousel owl-theme s_Product_carousel">
						<div class="single-prd-item">
							{% if product.image %}
								<img class="img-fluid" src="{{ product.image|thumbnail_url:'product_image' }}" alt="">
							{% else %}
							<img class="img-fluid" src="{% static 'assets/img/category/s-p1.jpg' %}" alt="">
							{% endif %}
						</div>
						<!-- <div class="single-prd-item">
							<img class="img-fluid" src="img/category/s-p1.jpg" alt="">
						</div>
						<div class="single-prd-item">
							<img class="img-fluid" src="img/category/s-p1.jpg" alt="">
						</div> -->
					</div>
				</div>
				<div class="col-lg-5 offset-lg-1">
					<div class="s_product_text">
						<h3>{{ product }}</h3>
						<h2>R$ {{ product.price }}</h2>
						<ul class="list">
							<li><a class="active" href="#"><span>Categoria</span> : {{ product.category }}</a></li>
						</ul>
						<p>{{ product.description }}</p>
						<div class="product_count">
							<a class="button primary-btn" href="{% url 'checkout:create_cartitem' product.slug %}">Adicionar ao Carrinho</a>
						</div>
						<p style="color: blue;"><b>Este site é um sistema demonstrativo, não efetue compras nele.</b></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--================End Single Product Area =================-->
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}
{% load static %}
{% load pagination %}

{% block title %}
    Listagem de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
    <section class="section-margin--small mb-5">
    <div class="container">
      <div class="row">
        <div class="col-xl-3 col-lg-4 col-md-5">
          <div class="sidebar-filter">
            </div>
          </div>
        </div>
        <div class="col-xl-12 col-lg-8 col-md-7">
          <section class="lattest-product-area pb-40 category-list">
            <div class="row">
                {% for product in product_list %}
                {% include "catalog/_product.html" %}
                {% endfor %}
            </div>
          </section>
          <!-- End Best Seller -->
        </div>
      </div>
    </div>
  </section>
	<!-- ================ category section end ================= -->


    {% pagination request paginator page_obj %}


{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(function () {
           $('.cart-item-add').on('click', function (e) {
               e.preventDefault()
              $.ajax({
                 url: $(this).attr('href'),
                  dataType: 'json',
                  success: function(data, textStatus, jqXHR){
                      alert(data.message);
                  }
              });
           });
        });
    </script>
{% endblock %}